# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

addr_book_strict = true

proxy_app = "tcp://127.0.0.1:16658"
moniker = "penguin"
fast_sync = true
db_backend = "leveldb"
log_level = "state:info,*:error"

[rpc]
laddr = "tcp://0.0.0.0:16657"

[p2p]
laddr = "tcp://0.0.0.0:16656"
seeds = ""
